### ISSUE TITLE
Added autogenous glow texture of material

### ISSUE THREAD

**Issue by FireFlieStudio** [Vwings/mmdbridge-material-importer#1]
Could U please tell me how can I add the autogenous glow texture of material to the model by eidit the script?

**Comment by Vwings** [comment]
Hello, @FireFlieStudio. If you want to change your material's texture, you can change it inside pmx editor and re run mmdbridge exporter, or if you want add emission effect in the blender material you can add a `ShaderNodeEmission` node to the NodeTree.   

However this script is used to create materials with BaseColor textures. There is not enough information to determine whether it needs to be created as a luminous material, I think it would be easier to modify the material after running this script.  

Please tell me your usecase. I will consider whether it is necessary to add it to the script logic.

**Comment by Vwings** [comment]
The issue is closed cause no reply, please feel free to reopen the issue.
